import Combine
import Foundation

enum AppEnvironment: String {
    case development
    case production

    var publicAppLink: URL {
        if let override = ProcessInfo.processInfo.environment["SUNNAD_PUBLIC_APP_LINK"],
           let url = URL(string: override), !override.isEmpty {
            return url
        }

        return URL(string: "https://www.sunnad.app")!
    }

    var privacyURL: URL {
        URL(string: "https://www.sunnad.app/privacy")!
    }

    var helpURL: URL {
        URL(string: "https://www.sunnad.app/help")!
    }

    var authRedirectURL: URL {
        if
            let override = ProcessInfo.processInfo.environment["SUNNAD_AUTH_REDIRECT_URL"],
            let url = URL(string: override.trimmingCharacters(in: .whitespacesAndNewlines)),
            !override.isEmpty
        {
            return url
        }

        return URL(string: "sunnad://auth-callback")!
    }

    struct SupabaseConfig {
        let url: URL
        let anonKey: String
    }

    struct OAuthConfig {
        let googleEnabled: Bool
        let appleEnabled: Bool
    }

    var oauthConfig: OAuthConfig {
        OAuthConfig(
            googleEnabled: resolveBoolEnv("SUNNAD_AUTH_GOOGLE_ENABLED", defaultValue: true),
            appleEnabled: resolveBoolEnv("SUNNAD_AUTH_APPLE_ENABLED", defaultValue: false)
        )
    }

    var supabaseConfig: SupabaseConfig? {
        func resolveEnv(_ names: [String]) -> String? {
            for name in names {
                guard let rawValue = ProcessInfo.processInfo.environment[name] else {
                    continue
                }

                let normalized = rawValue
                    .components(separatedBy: .newlines)
                    .map { $0.trimmingCharacters(in: .whitespacesAndNewlines) }
                    .first { !$0.isEmpty } ?? rawValue

                let trimmed = normalized
                    .trimmingCharacters(in: .whitespacesAndNewlines)
                    .trimmingCharacters(in: CharacterSet(charactersIn: "\"'"))

                if !trimmed.isEmpty {
                    return trimmed
                }
            }

            return nil
        }

        if
            let rawURL = resolveEnv(["SUNNAD_SUPABASE_URL", "SUPABASE_URL"]),
            let url = URL(string: rawURL),
            let anonKey = resolveEnv([
                "SUNNAD_SUPABASE_ANON_KEY",
                "SUPABASE_ANON_KEY",
                "SUNNAD_SUPABASE_PUBLISHABLE_KEY",
                "SUPABASE_PUBLISHABLE_KEY"
            ])
        {
            return SupabaseConfig(url: url, anonKey: anonKey)
        }

        #if DEBUG
        // Local-debug fallback so auth still works even when Xcode scheme env vars are missing.
        // This key is the default local Supabase anon key generated by CLI projects.
        let fallbackKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZS1kZW1vIiwicm9sZSI6ImFub24iLCJleHAiOjE5ODM4MTI5OTZ9.CRXP1A7WOeoJeXxjNni43kdQwgnWNReilDMblYTn_I0"
        let fallbackPorts = [55421, 54321]
        if resolveEnv(["SUNNAD_DISABLE_LOCAL_SUPABASE_FALLBACK"]) != "1" {
            for port in fallbackPorts {
                if let url = URL(string: "http://127.0.0.1:\(port)") {
                    return SupabaseConfig(url: url, anonKey: fallbackKey)
                }
            }
        }
        #endif

        return nil
    }

    static var current: AppEnvironment {
        #if DEBUG
        return .development
        #else
        return .production
        #endif
    }

    private func resolveBoolEnv(_ key: String, defaultValue: Bool) -> Bool {
        guard let raw = ProcessInfo.processInfo.environment[key]?.trimmingCharacters(in: .whitespacesAndNewlines),
              !raw.isEmpty else {
            return defaultValue
        }

        switch raw.lowercased() {
        case "1", "true", "yes":
            return true
        case "0", "false", "no":
            return false
        default:
            return defaultValue
        }
    }
}
